export type UserRole = 'USER' | 'ADMIN'

export interface UserSession {
  id: number
  username: string
  fullName: string
  email: string
  role: UserRole
}

export interface PageResponse<T> {
  content: T[]
  totalElements: number
  totalPages: number
  currentPage: number
  pageSize: number
}

export interface CategoryRef {
  code: string
  label: string
}

export interface Listing {
  id: number
  title: string
  description: string
  category: CategoryRef
  catalogItemId?: number
  price: number
  stock: number
  imageUrl?: string
  active: boolean
  ownerId: number
  ownerName: string
  createdAt: string
  updatedAt: string
}

export interface ListingRequest {
  title: string
  description: string
  categoryCode: string
  price: number
  stock: number
  imageUrl?: string
}

export interface ChatConversationSummary {
  id: number
  userAId: number
  userAName: string
  userBId: number
  userBName: string
  lastMessagePreview?: string
  lastMessageAt?: string
  unreadCount: number
  updatedAt: string
}

export interface ChatMessage {
  id: number
  conversationId: number
  senderId: number
  senderName: string
  content: string
  autoGenerated: boolean
  createdAt: string
}

export interface ChatUnreadCount {
  unreadCount: number
}

export interface ChatSocketEvent {
  type: 'CHAT_MESSAGE_CREATED' | 'CHAT_UNREAD_UPDATED'
  conversationId?: number
  message?: ChatMessage
  unreadCount?: number
}

export interface IotHighlight {
  id: number
  title: string
  description: string
  icon: string
  displayOrder: number
}

export interface IotHighlightUpdateRequest {
  title: string
  description: string
  icon: string
  displayOrder: number
}

export interface IotContent {
  id: number
  heroTitle: string
  heroSubtitle: string
  heroImageUrl?: string
  primaryCtaLabel: string
  primaryCtaHref: string
  highlights: IotHighlight[]
}

export interface IotContentUpdateRequest {
  heroTitle: string
  heroSubtitle: string
  heroImageUrl?: string
  primaryCtaLabel: string
  primaryCtaHref: string
  highlights: IotHighlightUpdateRequest[]
}

export type IotSegment = 'COMPONENTS' | 'SAMPLE_PRODUCTS' | 'SERVICES'

export interface IotOverviewResponse {
  heroTitle: string
  heroSubtitle: string
  heroImageUrl?: string
  primaryCtaLabel: string
  primaryCtaHref: string
  highlights: IotHighlight[]
  categoryOptions: CategoryRef[]
  listings: PageResponse<Listing>
}

export interface IotItemResponse {
  id: number
  slug?: string
  catalogItemId?: number
  title: string
  description?: string
  category?: CategoryRef
  price: number
  stock: number
  imageUrl?: string
  purchasable?: boolean
  createdAt: string
}

export interface IotSampleProject {
  id: number
  slug: string
  title: string
  summary?: string
  description?: string
  mainComponents: string[]
  difficulty?: string
  buildTime?: string
  mcuSoc?: string
  connectivity?: string
  projectPath: string
  readmePath: string
  pinoutPath: string
  principlePath: string
  sourcesPath: string
  category: CategoryRef
  catalogItemId?: number
  price: number
  stock: number
  imageUrl?: string
  active: boolean
  purchasable: boolean
  createdAt: string
  updatedAt: string
}

export interface IotSampleProjectRequest {
  slug: string
  title: string
  categoryCode: string
  summary?: string
  description?: string
  mainComponents: string[]
  difficulty?: string
  buildTime?: string
  mcuSoc?: string
  connectivity?: string
  projectPath: string
  readmePath: string
  pinoutPath: string
  principlePath: string
  sourcesPath: string
  price: number
  stock: number
  imageUrl?: string
  active: boolean
}

export interface CartItem {
  catalogItemId: number
  sourceType: 'LISTING' | 'IOT_COMPONENT' | 'IOT_SAMPLE'
  sourceRefId: number
  title: string
  price: number
  quantity: number
  imageUrl?: string
  subtotal: number
}

export interface Cart {
  items: CartItem[]
  totalAmount: number
  warnings?: string[]
}

export type OrderStatus = 'PENDING' | 'CONFIRMED' | 'PROCESSING' | 'SHIPPING' | 'DELIVERED' | 'CANCELLED'

export interface OrderItem {
  catalogItemId: number
  sourceType: 'LISTING' | 'IOT_COMPONENT' | 'IOT_SAMPLE'
  sourceRefId: number
  title: string
  quantity: number
  unitPrice: number
  subtotal: number
}

export interface Order {
  id: number
  orderCode: string
  customerName: string
  customerEmail: string
  customerAddress: string
  status: OrderStatus
  totalAmount: number
  items: OrderItem[]
  createdAt: string
}

export interface Event {
  id: number
  title: string
  summary?: string
  description?: string
  startAt: string
  endAt: string
  location: string
  type: string
  fee: number
  imageUrl?: string
  active: boolean
  createdAt: string
}

export interface EventRequest {
  title: string
  summary?: string
  description?: string
  startAt: string
  endAt: string
  location: string
  type: string
  fee: number
  imageUrl?: string
  active?: boolean
}

export type EventRegistrationStatus = 'REGISTERED' | 'CONFIRMED' | 'CANCELLED'

export interface EventRegistration {
  id: number
  eventId: number
  eventTitle: string
  name: string
  email: string
  phone?: string
  note?: string
  status: EventRegistrationStatus
  createdAt: string
}

export interface FAQItem {
  id: number
  category: string
  question: string
  answer: string
  displayOrder: number
}

export type SupportTicketStatus = 'PENDING' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED'

export interface SupportTicket {
  id: number
  ticketCode: string
  name: string
  email: string
  subject: string
  category: string
  message: string
  status: SupportTicketStatus
  adminReply?: string
  createdAt: string
  updatedAt: string
  repliedAt?: string
}
